"""relationship_cashback_seller

Revision ID: 00e24dcab986
Revises: 4cd31f05cc5c
Create Date: 2024-03-03 19:02:06.799414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e24dcab986'
down_revision = '4cd31f05cc5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
