"""removed

Revision ID: 260279d6938d
Revises: f2ee2fc0ff90
Create Date: 2024-02-27 00:34:38.128165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '260279d6938d'
down_revision = 'f2ee2fc0ff90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_user_chat_fk_chat', 'user', type_='foreignkey')
    op.drop_column('user', 'language_code')
    op.drop_column('user', 'user_chat_fk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_chat_fk', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('language_code', postgresql.ENUM('EN', 'RU', 'UK', name='locales'), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_user_user_chat_fk_chat', 'user', 'chat', ['user_chat_fk'], ['id'])
    # ### end Alembic commands ###
