"""updated

Revision ID: 28269d00834c
Revises: ecc14d1780b1
Create Date: 2024-02-28 19:05:28.470431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28269d00834c'
down_revision = 'ecc14d1780b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowedseller',
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allowedseller'))
    )
    op.create_table('seller',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fullname', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seller')),
    sa.UniqueConstraint('user_id', name=op.f('uq_seller_user_id'))
    )
    op.create_table('cashback',
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], name=op.f('fk_cashback_seller_id_seller'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cashback')),
    sa.UniqueConstraint('check_id', name=op.f('uq_cashback_check_id'))
    )
    op.create_table('product',
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], name=op.f('fk_product_seller_id_seller'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('check_id', name=op.f('uq_product_check_id'))
    )
    op.create_table('client',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fullname', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_client_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client')),
    sa.UniqueConstraint('user_id', name=op.f('uq_client_user_id'))
    )
    op.drop_table('chat')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.create_table('chat',
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('chat_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chat_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_user'], ['user.id'], name='fk_chat_chat_user_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_chat'),
    sa.UniqueConstraint('chat_id', name='uq_chat_chat_id')
    )
    op.drop_table('client')
    op.drop_table('product')
    op.drop_table('cashback')
    op.drop_table('seller')
    op.drop_table('allowedseller')
    # ### end Alembic commands ###
