"""cashback_to_client

Revision ID: 29ae292a9970
Revises: aab511c931fc
Create Date: 2024-03-26 14:16:22.743869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ae292a9970'
down_revision = 'aab511c931fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashback', sa.Column('client_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('fk_cashback_seller_id_seller', 'cashback', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cashback_client_id_client'), 'cashback', 'client', ['client_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('cashback', 'seller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashback', sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_cashback_client_id_client'), 'cashback', type_='foreignkey')
    op.create_foreign_key('fk_cashback_seller_id_seller', 'cashback', 'seller', ['seller_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('cashback', 'client_id')
    # ### end Alembic commands ###
