"""type_change

Revision ID: 335b314c79e4
Revises: 038ca19eec15
Create Date: 2024-03-07 17:15:52.599178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335b314c79e4'
down_revision = '038ca19eec15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase', 'client_id', type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
