"""using_index

Revision ID: 4cd31f05cc5c
Revises: e63230d1cd80
Create Date: 2024-03-03 16:42:53.533034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd31f05cc5c'
down_revision = 'e63230d1cd80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_client_user_id', 'client', type_='unique')
    op.create_index(op.f('ix_client_user_id'), 'client', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_user_id'), table_name='client')
    op.create_unique_constraint('uq_client_user_id', 'client', ['user_id'])
    # ### end Alembic commands ###
