"""changed_foreignkey

Revision ID: 5a8d9bdada1e
Revises: 28269d00834c
Create Date: 2024-02-29 16:09:28.811177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8d9bdada1e'
down_revision = '28269d00834c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cashback_seller_id_seller', 'cashback', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cashback_seller_id_seller'), 'cashback', 'seller', ['seller_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('fk_product_seller_id_seller', 'product', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_seller_id_seller'), 'product', 'seller', ['seller_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_product_seller_id_seller'), 'product', type_='foreignkey')
    op.create_foreign_key('fk_product_seller_id_seller', 'product', 'seller', ['seller_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_cashback_seller_id_seller'), 'cashback', type_='foreignkey')
    op.create_foreign_key('fk_cashback_seller_id_seller', 'cashback', 'seller', ['seller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
