"""type_change

Revision ID: 897efa550ca3
Revises: f19609a832be
Create Date: 2024-03-07 17:22:11.962805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897efa550ca3'
down_revision = 'f19609a832be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_purchase_product_id_product'), 'purchase', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_purchase_product_id_product'), 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'product_id')
    # ### end Alembic commands ###
