"""length_change

Revision ID: aab511c931fc
Revises: 86ca3027c12d
Create Date: 2024-03-07 23:38:09.979988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab511c931fc'
down_revision = '86ca3027c12d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
