"""type_change

Revision ID: bdd59269476c
Revises: eabaa94f10fd
Create Date: 2024-03-07 17:23:40.252541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd59269476c'
down_revision = 'eabaa94f10fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('client_id', sa.BIGINT(), nullable=True))
    op.create_foreign_key(op.f('fk_purchase_client_id_client'), 'purchase', 'client', ['client_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_purchase_client_id_client'), 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'client_id')
    # ### end Alembic commands ###
