"""added_qr_cols

Revision ID: e5a24f3fd29e
Revises: e213b32d41c1
Create Date: 2024-02-29 17:31:53.241663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a24f3fd29e'
down_revision = 'e213b32d41c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('qr_image_path', sa.Text(), nullable=False))
    op.add_column('product', sa.Column('qr_image_file_id', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'qr_image_file_id')
    op.drop_column('product', 'qr_image_path')
    # ### end Alembic commands ###
