"""new_pk_in_seller

Revision ID: e63230d1cd80
Revises: e5a24f3fd29e
Create Date: 2024-03-01 02:12:02.938860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63230d1cd80'
down_revision = 'e5a24f3fd29e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
