"""type_change

Revision ID: eabaa94f10fd
Revises: 897efa550ca3
Create Date: 2024-03-07 17:22:52.296765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabaa94f10fd'
down_revision = '897efa550ca3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_purchase_client_id_client', 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('client_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_purchase_client_id_client', 'purchase', 'client', ['client_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
