"""language_code_returned

Revision ID: ecc14d1780b1
Revises: 260279d6938d
Create Date: 2024-02-27 17:21:53.899259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc14d1780b1'
down_revision = '260279d6938d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language_code', sa.Enum('EN', 'RU', 'UZ', name='locales'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'language_code')
    # ### end Alembic commands ###
