"""type_change

Revision ID: f19609a832be
Revises: 335b314c79e4
Create Date: 2024-03-07 17:21:45.605960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19609a832be'
down_revision = '335b314c79e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_purchase_product_id_product', 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_purchase_product_id_product', 'purchase', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
